Header and headline section
kamzzy/portfolioSetup pull request #1
Opened 2022-03-17 15:54 UTC by kamzzy

Header and headline section of the portfolio project.
The template used for this project is **Template 3**

2022-03-17 18:33 UTC, BenMukebo requested changes
### Hi *** @Kamzzy, ***

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Github flow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Professional README ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 18:33 UTC, BenMukebo commented on index.html
> +            <h1>Welcome</h1>
- [ ] Please wrap this section in an `a` tag as this logo will be used as a link to the home page
- [ ] You should consider changing that `h1` to something hx below as you already have `h1` for your title in the headline section

2022-03-17 18:33 UTC, BenMukebo commented on index.html
> +               <span> I'm a software developer</span>
- [ ] Please change that span to an `h2` tag, it is supposed to be the subtitle

2022-03-17 18:33 UTC, BenMukebo commented on index.html
> +           </h3>
- [ ] Great job, you have done a big work but let's make a few changes; as for here, please use a `p` tag instead of this h3,

2022-03-17 18:33 UTC, BenMukebo commented on index.html
> +                   <img src="icons/angellist.png" alt="angellist_link">
- [ ] Let's change something here too, from that `h3` tag, please change it to a `ul` tag and wrap each an inside a `li` tag then 😄 I think it makes sense doing that
- [ ] Please use proper link to each of your social medial account

2022-03-18 00:03 UTC, smunozmo requested changes
Hi @kamzzy, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.

 ## Required Changes ♻️

- [ ] The overall design is still looking different from the original template, I would suggest fixing the background image size, using the right font family and font size for your headings and paragraphs, and last, increasing the space between the social logos, here is the comparison:

- Your desing
![Captura de pantalla 2022-03-17 a la(s) 6 56 01 p  m](https://user-images.githubusercontent.com/83717285/158912742-8a1cffd0-7da0-4071-95ee-00163c4e01e3.png)

- Figma Template
![image](https://user-images.githubusercontent.com/83717285/158912797-c76651a2-6d51-47aa-9352-ea6f9bd161eb.png)

👉  _Check the comments under the review._ 👈 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 00:03 UTC, smunozmo commented on index.html
> +                </li>
- [ ] Great job updating the links and using the `li` tags, however, this `li` tag should be wrapped inside an `ul` tag.  Here's is an [example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li).

2022-03-18 16:17 UTC, vic778 approved these changes
### STATUS: APPROVED  :+1: : 
Hi @kamzzy  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Descriptive commits and correct use of the Git Flow :fire:
- [x] :white_check_mark: page titles :white_check_mark: text headings :white_check_mark: color contrast :white_check_mark: resize :white_check_mark: basic structure of the page 

## Required Changes ♻️
N/A

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 16:17 UTC, vic778 commented on index.html
> +            <a class="logo" href="">Welcome</a>
- [OPTIONAL] kindly add the font-style of your logo so that it looks like the Figma model

2022-03-18 16:17 UTC, vic778 commented on style.css
> +}
- [OPTIONAL] kindly make sure you fix the padding and the margin of your body. there is an empty space after the flesh of your page

2022-03-18 22:44 UTC, kamzzy commented
Hi @vic778  thanks for the approval, please this project is still reflected as incomplete on my dashboard, can you kindly let me know if this is from your end or who I should contact to sort it out thanks

2022-03-19 04:56 UTC, vic778 commented
Let me reach the Senior CR  they will work on it please

2022-03-20 02:31 UTC, merged